"""paper added page span

Revision ID: 038f0b77354f
Revises: 595797dd5a9f
Create Date: 2024-11-16 08:26:38.670378

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038f0b77354f'
down_revision: Union[str, None] = '595797dd5a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('merged_table_start_page', sa.Integer(), nullable=True))
    op.add_column('paper', sa.Column('merged_table_end_page', sa.Integer(), nullable=True))
    op.add_column('paper', sa.Column('publish_month', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'publish_month')
    op.drop_column('paper', 'merged_table_end_page')
    op.drop_column('paper', 'merged_table_start_page')
    # ### end Alembic commands ###
