"""candidate-table add headers

Revision ID: 3a4d07a8c5cd
Revises: 36eb0fa9e3ee
Create Date: 2024-11-15 21:58:52.294462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3a4d07a8c5cd'
down_revision: Union[str, None] = '36eb0fa9e3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_table', sa.Column('headers', sa.JSON(), nullable=True))
    op.drop_column('target_table', 'standardized_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_table', sa.Column('standardized_data', sqlite.JSON(), nullable=True))
    op.drop_column('target_table', 'headers')
    # ### end Alembic commands ###
