"""paper fixed

Revision ID: 595797dd5a9f
Revises: e52c42a09ed5
Create Date: 2024-11-16 06:03:39.854846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595797dd5a9f'
down_revision: Union[str, None] = 'e52c42a09ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('publish_month_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'publish_month_verified')
    # ### end Alembic commands ###
