"""paper added merged_criterion_table

Revision ID: 87878f444073
Revises: 46808c5b1049
Create Date: 2024-11-15 22:28:47.086935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87878f444073'
down_revision: Union[str, None] = '46808c5b1049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('merged_criterion_table', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'merged_criterion_table')
    # ### end Alembic commands ###
