"""paper refactor fields

Revision ID: a242690f5edf
Revises: 3a4d07a8c5cd
Create Date: 2024-11-15 22:08:41.011525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a242690f5edf'
down_revision: Union[str, None] = '3a4d07a8c5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('criterion_tables_count', sa.Integer(), nullable=True))
    op.drop_column('paper', 'has_criterion_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('has_criterion_table', sa.BOOLEAN(), nullable=True))
    op.drop_column('paper', 'criterion_tables_count')
    # ### end Alembic commands ###
