"""paper added publish month

Revision ID: ac41b18384f4
Revises: e52c42a09ed5
Create Date: 2024-11-16 05:32:53.569540

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac41b18384f4'
down_revision: Union[str, None] = 'e52c42a09ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding it
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('paper')]
    if 'publish_month' not in columns:
        op.add_column('paper', sa.Column('publish_month', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('paper', sa.Column('publish_month_verified', sa.Boolean(), nullable=False))
     # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'publish_month_verified')
    op.drop_column('paper', 'publish_month')
    # ### end Alembic commands ###
