"""paper added merged count

Revision ID: e52c42a09ed5
Revises: 87878f444073
Create Date: 2024-11-16 00:06:20.673463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52c42a09ed5'
down_revision: Union[str, None] = '87878f444073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('merged_tables_count', sa.Integer(), nullable=True))
    op.add_column('paper', sa.Column('merged_rows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'merged_rows_count')
    op.drop_column('paper', 'merged_tables_count')
    # ### end Alembic commands ###
